-- User: profile fields
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "coverImage" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pronouns" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "socials" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "roles" TEXT[] NOT NULL DEFAULT ARRAY['user'::text];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "featuredCharacterIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "featuredFriendUsernames" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

-- Character: designer + extra fields
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "isDesigner" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "designerCredit" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "orientation" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "customFieldName" TEXT;
